{
    "name": "Fleet GPS Tracker",
    "version": "19.0.1.0.0",
    "category": "Fleet",
    "summary": "Simulated GPS vehicle tracking with Google Maps visualization",
    "author": "Mosent Group",
    "license": "LGPL-3",
    "depends": ["base", "web"],
    "data": [
        "security/ir.model.access.csv",
        "wizards/gps_simulate_wizard_views.xml",
        "wizards/gps_playback_wizard_views.xml",
        "views/gps_vehicle_views.xml",
        "views/gps_coordinate_views.xml",
        "views/res_config_settings_views.xml",
        "views/gps_map_menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "fleet_gps_tracker/static/src/gps_map/gps_map_status.scss",
            "fleet_gps_tracker/static/src/gps_map/gps_map_utils.js",
            "fleet_gps_tracker/static/src/gps_map/gps_icon_image_field.js",
            "fleet_gps_tracker/static/src/gps_map/gps_icon_image_field.xml",
            "fleet_gps_tracker/static/src/gps_map/gps_vehicle_map_field.js",
            "fleet_gps_tracker/static/src/gps_map/gps_vehicle_map_field.xml",
            "fleet_gps_tracker/static/src/gps_map/gps_map_overview_action.js",
            "fleet_gps_tracker/static/src/gps_map/gps_map_overview_action.xml",
            "fleet_gps_tracker/static/src/gps_map/gps_route_playback_action.js",
            "fleet_gps_tracker/static/src/gps_map/gps_route_playback_action.xml",
        ],
    },
    "installable": True,
    "application": True,
}
